# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42ab6799bb019b8821ea3b36263f70b3316cef5d69f20c92cb69b9f34721a614265358bfbda178901bd67f76caa63e3045b562ae5b6d6901593d724d0d0a97e9

test:
  secret_key_base: ee2d79bb9aee2d64dcc3d6c3d94b03b8ead8a8737f074c4c7209cfc476eeb1f297ed47e1d915a200db928c58e4cff10212c55258cc6753cd0bf076d22f7a9e49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
